### ISSUE TITLE
Could we add an installation and getting started guide?

### ISSUE THREAD

**Issue by Isaac2709** [petrovicstefanrs/30_seconds_of_knowledge#105]
I have been trying to set up the project in order to create content or introduce fixes but I'm getting many errors using only the npm install and start so I'm wondering if there is a possibility of creating an installation and getting started guide that explains this process?

**Comment by petrovicstefanrs** [comment]
I started rewriting the project to use functional (/w hooks( instead of class-based components and I'm updating webpack and react versions. This will take some time, but after it's done I should have a more stable version of the extension to work with. This one is pretty tedious to work with, which is why I decided to rewrite it in the first place.
