### ISSUE TITLE
Add enkidevs curriculum

### ISSUE THREAD

**Issue by obrmao** [petrovicstefanrs/30_seconds_of_knowledge#11]
[Enki](https://enki.com/) is a very good mobile app, similar in the idea to 30 seconds of knowledge - you learn a new API for a couple of minutes each day. Their curriculum is open-sourced here: https://github.com/enkidevs/curriculum. A good idea would be to merge the content here to expand the range of covered topics.

**Comment by petrovicstefanrs** [comment]
@obrmao Hey, thank you so much for the tip. I guess I'll contact them and ask if they wouldn't mind me using their data. Thanks again!

**Comment by petrovicstefanrs** [comment]
Unfortunately, in order to use data from Enki, the application shouldn't accumulate any revenue. If I did that I wouldn't be able to support it anymore. My current goal is to assign as much time and resources as I can to development of this extension. This means unfortunately, that opt-ing out of donations from the  extension would also mean that I can't afford its hosting or any further development. For now this issue will be closed but revisited in the future, once the extension is self-sustaining.
