### ISSUE TITLE
Chrome Extension: Bookmarks

### ISSUE THREAD

**Issue by sirberus** [petrovicstefanrs/30_seconds_of_knowledge#15]
Please consider letting us add simple bookmarks - just a label and URL would be fine!

**Comment by petrovicstefanrs** [comment]
@sirberus Left this open so far because I wanted to think about it a bit more. But I will have to close it for now. The extension is starting to get more and more functionality directly related to the base idea of what it's meant to do and adding this now would seam like unnecessary bloating. Unfortunately I'm just not sure how to add this to elegantly fit the rest of the extension. 

If however the need for this gets bigger I will reopen the issue.
