### ISSUE TITLE
Make builds for other browsers.

### ISSUE THREAD

**Issue by doncullen** [petrovicstefanrs/30_seconds_of_knowledge#2]
Possible to have this ported to Firefox too?

See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by petrovicstefanrs** [comment]
@doncullen Hey, thanks for the resource. I will definitely look into it. I do plan to do a firefox version for the first major release. I will leave this issue here as a reminder and as a way for you to get notified once its done.

**Comment by nero2009** [comment]
Hi I have ported a couple chrome extensions to firefox, I might be able to help with this

**Comment by petrovicstefanrs** [comment]
@nero2009 Hey, that would be great, but tell me what did you have in mind? A shared codebase with the main extension just different build processes or a completely separate codebase?

**Comment by nero2009** [comment]
@petrovicstefanrs A shared codebase with different branches would be Ok, anyone that works for you really.
I am currently working on this issue and making progress, albeit rather slowly

**Comment by nero2009** [comment]
@petrovicstefanrs apparently `lookbehind` and `lookahead` are  not supported by firefox so I have to rewrite  this regex in the `snippets.js` but I dont really understand what the regex does

```
const SNIPPET_CODE_REGEX = {
	html: new RegExp(/(?<=\`\`\`html)(.*?)(?=\`\`\`)/, 'gsm'),
	css: new RegExp(/(?<=\`\`\`css)(.*?)(?=\`\`\`)/, 'gsm'),
	js: new RegExp(/(?<=\`\`\`js)(.*?)(?=\`\`\`)/, 'gsm'),
};
```
I am not really good with regex

**Comment by petrovicstefanrs** [comment]
@nero2009 Yep, still no positive lookbehind in FF, i was aware. The regex in SNIPPET_CODE_REGEX is used to extract code snippets from their markdown files. I can write regex that will work in FF, if that would help you. Also I want to see how you setup the project on your branch (just give me a link here).

**Comment by nero2009** [comment]
@petrovicstefanrs [Link](https://github.com/nero2009/30_seconds_of_knowledge/tree/feature/firefox-version), It is still your setup and build process but I am just make changes to make it compatible with firefox.
I think it would be better if you can write a regex that works on Firefox cos I haven't made any progress.

**Comment by petrovicstefanrs** [comment]
@nero2009 I've gone through your branch. I see that you only started preparing for changes to be able to create a firefox version. Maybe the best course of action would be for me to first opt-out of any chrome specific api stuff and rewrite everything to use WebExtensions api. that way we may even be able to build for firefox without any additional changes, however it there is going to be some additional work needed then we can split the tasks here and work from there.

I'm preparing a new release for the weekend, and I'll try to rewrite everything to use WebExtensions api. So that after this release we can work towards firefox and safari versions.

**Comment by nero2009** [comment]
@petrovicstefanrs That would be awesome
