### ISSUE TITLE
Please add jQuery snippets

### ISSUE THREAD

**Issue by TheRealBastiaan** [petrovicstefanrs/30_seconds_of_knowledge#34]
Dear @petrovicstefanrs 

Can you please add jQuery snippets. It is something I’m currently learning and trying to get better at. I think that more users are interested in this.

Examples that you can add; Smooth scrolling, Form validation.

**Comment by petrovicstefanrs** [comment]
@TheRealBastiaan Hi, thanks for the proposal, but unfortunately due to decreasing popularity of jQuery I don't think investing time into those snippets would be the best idea. Most of the snippets from javascript will work inside jQuery as well so it would be a rather redundant addition. In case of other JS frameworks such as React which have their own largely different ecosystems it makes sense to have separate snippets for them, but that is not the case for jQuery. 

With all that being said, if I find a painless solution to add this I will, but until then I will mark this issue as "wontfix" for now.
