### ISSUE TITLE
feature request: working code snippets in an web editor / ide

### ISSUE THREAD

**Issue by muescha** [petrovicstefanrs/30_seconds_of_knowledge#48]
i would like to have also a warking code snippet at codepen.io or similar online code editors...

**Comment by petrovicstefanrs** [comment]
Hey, @muescha currently I can only do this out of the box for css snippets, for any other language I would need to have all snippets expanded with a working example that would then be pushed to a website like codepen like it works with css now. However since there are 600+ snippets and I can't get that much time due to my day job, It really depends if the community is up to it to start adding these.

For now I will leave this open, and flag it as help needed if someone wants to run some ideas through on how they would implement it.

**Comment by muescha** [comment]
Just add to the template some "try it now link" and new snippets are comes with working examples ...

**Comment by petrovicstefanrs** [comment]
@muescha well it's not easy as that. Most of the examples would need some setting up to make sense when provided as examples on mentioned websites. Adding that link is the easy part, still most of the snippets would need additional code to be working examples, and those need to be written manually. If I happen to find people willing to help on this feature I will expand on it until then, I'm not sure I'll be able to do much on my own.
