### ISSUE TITLE
Feature:  Add ability to browse all available snippets

### ISSUE THREAD

**Issue by brentonhouse** [petrovicstefanrs/30_seconds_of_knowledge#66]
I can see the option to browse saved snippets but not to see all snippets (preferably by category).   Would be great to have this feature!

**Comment by petrovicstefanrs** [comment]
Not sure how this would benefit the extension, it feels like adding functionality that is changing the purpose of the extension ( to be a quick random coding tip you can read in a short amount of time ) 

I'm saying this because the browsing could still be done on websites specializing in every one of the languages the extension has. For css you could visit 30 seconds of css. I could add quick links for every one of these, but maybe a better solution would be to create a HUB for all the languages which would act as a site map for all these website.
