### ISSUE TITLE
Interested in using Laravel/Vue Snippits?

### ISSUE THREAD

**Issue by Zac-Zajdel** [petrovicstefanrs/30_seconds_of_knowledge#84]
Hello,

My name is Zac. I have been developing in Laravel and Vue for my current job and in my free time. I absolutely love this extension and think it's such a unique concept.  I would like to begin my journey into contributing to open-source projects and I think I found the one. I would like to help and add code snippits of Laravel and Vue functionality. Would either of these frameworks be considered? 

Best,
Zac Zajdel

**Comment by petrovicstefanrs** [comment]
Hello Zac,

Glad you are interested in the project and would like to contribute. The thing is, 30SOK is just a browser extension built on top of 30 Seconds Of Code projects. There is an org here on git [30 seconds](https://github.com/30-seconds). They have the best resources to help you start your own 30 seconds project. You can talk to @Chalarangelo and see if he can help you out. Once your project is live and a part of their organization I could add it to the extension as well.

Since this extension is a weekend project for me, I think you'd be in better hands with 30 seconds guys. Also, even if this project dies one day, your project will be live in the 30 seconds org.

Best regards mate.
