### ISSUE TITLE
Feature request: Safari Extension

### ISSUE THREAD

**Issue by davidpravst** [petrovicstefanrs/30_seconds_of_knowledge#98]
I love 30 seconds of knowledge. I recently switched from Chrome to Safari. Is it possible to also release Safari extension in future release?

**Comment by petrovicstefanrs** [comment]
I'll try to make it work

**Comment by petrovicstefanrs** [comment]
@davidpravst I managed to make the new rewritten extension work with Safari 15 and up. So once I release v2 for other browsers I'll release it for Safari as well. That might take a bit more time since I have no idea how to release safari extensions but I'll figure it out :D.

Anyway for more context around v2 for extension you can read my updates on this issue https://github.com/petrovicstefanrs/30_seconds_of_knowledge/issues/85
